.TH "rasPi-EmergencyStation Directory Reference" 3 "Mon Jan 25 2016" "Version 0.1" "Skynet - Emergency station" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rasPi-EmergencyStation Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBmain\&.c\fP"
.br
.RI "\fIMain file and functions of the emergency station application\&. \fP"
.ti -1c
.RI "file \fBmain\&.h\fP"
.br
.RI "\fIMain file's headers of the emergency station application\&. \fP"
.ti -1c
.RI "file \fBmcastMessaging\&.c\fP"
.br
.RI "\fIFIle containing all the definition of the functions related to multicast communication\&. \fP"
.ti -1c
.RI "file \fBmcastMessaging\&.h\fP"
.br
.RI "\fIFIle containing all the headers of the functions related to multicast communication\&. \fP"
.ti -1c
.RI "file \fBmessageParser\&.c\fP"
.br
.RI "\fIMessage parser functions definition\&. \fP"
.ti -1c
.RI "file \fBmessageParser\&.h\fP"
.br
.RI "\fIMessage parser function headers\&. \fP"
.ti -1c
.RI "file \fBmsgBuffers\&.c\fP"
.br
.RI "\fIFile containing the definitions of all functions related to the message mailboxes\&. \fP"
.ti -1c
.RI "file \fBmsgBuffers\&.h\fP"
.br
.RI "\fIFile containing the headers of all functions related to the message mailboxes\&. \fP"
.ti -1c
.RI "file \fBstationActions\&.c\fP"
.br
.RI "\fIFIle containing all the station action definitions\&. \fP"
.ti -1c
.RI "file \fBstationActions\&.h\fP"
.br
.RI "\fIFIle containing all the station action headers\&. \fP"
.ti -1c
.RI "file \fBtcpServerSocketComm\&.c\fP"
.br
.RI "\fIServer connection related function headers\&. \fP"
.ti -1c
.RI "file \fBtcpServerSocketComm\&.h\fP"
.br
.RI "\fIServer connection related function definitions\&. \fP"
.ti -1c
.RI "file \fBtcpVehicleSocketComm\&.c\fP"
.br
.RI "\fIVehicle connection server related function definitions\&. \fP"
.ti -1c
.RI "file \fBtcpVehicleSocketComm\&.h\fP"
.br
.RI "\fIVehicle connection server's headers\&. \fP"
.in -1c
