.TH "rasPi-EmergencyStation/main.h" 3 "Thu Jan 21 2016" "Version 0.1" "Emergency station" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rasPi-EmergencyStation/main.h \- Main file's headers of the emergency station application\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <signal\&.h>\fP
.br
\fC#include 'structures\&.h'\fP
.br
\fC#include 'messageParser\&.h'\fP
.br
\fC#include 'msgBuffers\&.h'\fP
.br
\fC#include 'stationActions\&.h'\fP
.br
\fC#include 'tcpServerSocketComm\&.h'\fP
.br
\fC#include 'tcpVehicleSocketComm\&.h'\fP
.br

.SH "Detailed Description"
.PP 
Main file's headers of the emergency station application\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for Emergency station from the source code\&.
