.TH "rasPi-EmergencyStation/mcastMessaging.c" 3 "Mon Jan 25 2016" "Version 0.1" "Skynet - Emergency station" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rasPi-EmergencyStation/mcastMessaging.c \- FIle containing all the definition of the functions related to multicast communication\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'mcastMessaging\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBMCM_initMcastServer\fP ()"
.br
.RI "\fIIntialize the multicast UDP listener and sender\&. \fP"
.ti -1c
.RI "void \fBMCM_shutdownMcastServer\fP ()"
.br
.RI "\fIClose the sockets and stop all threads of multicast comunication\&. \fP"
.ti -1c
.RI "void \fBMCM_initSockets\fP ()"
.br
.RI "\fIInitialize the sockets for multicast communication\&. \fP"
.ti -1c
.RI "struct in_addr \fBMCM_calcStationAddress\fP ()"
.br
.RI "\fICaltulate address for the multicast group\&. \fP"
.ti -1c
.RI "void \fBMCM_initStationGroup\fP ()"
.br
.RI "\fISets the station group to the one that we have calculated first\&. \fP"
.ti -1c
.RI "void \fBMCM_initGeneralGroup\fP ()"
.br
.RI "\fIInitialize the general groups\&. \fP"
.ti -1c
.RI "void * \fBMCM_listenerThread\fP (void *args)"
.br
.RI "\fIThread for listening to messages coming from the general multicast group\&. \fP"
.ti -1c
.RI "void * \fBMCM_senderThread\fP (void *args)"
.br
.RI "\fIThread for sending the messages to the station multicast group\&. \fP"
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBMCM_serverStats\fP \fBmcmServerStats\fP"
.br
.RI "\fIVariable to store all the multicast server info\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
FIle containing all the definition of the functions related to multicast communication\&. 


.SH "Function Documentation"
.PP 
.SS "struct in_addr MCM_calcStationAddress ()"

.PP
Caltulate address for the multicast group\&. Calculates the group address based on the ID of the station\&. The address is changed to little endian first to add the id value\&. Then is converted back\&. 
.PP
\fBReturns:\fP
.RS 4
The in_addr structure with the address\&. 
.RE
.PP

.SS "void MCM_initGeneralGroup ()"

.PP
Initialize the general groups\&. Sets the kernel to join the general multicast group\&. 
.SS "void MCM_initMcastServer ()"

.PP
Intialize the multicast UDP listener and sender\&. Initializes all the sockets, threads and structures needed for the multicast communications\&. 
.SS "void MCM_initSockets ()"

.PP
Initialize the sockets for multicast communication\&. Initializes both the sockets to listen to the general group and the socket to send the messages to the station group\&. 
.SS "void MCM_initStationGroup ()"

.PP
Sets the station group to the one that we have calculated first\&. 
.PP
\fBSee also:\fP
.RS 4
\fBMCM_calcStationAddress\fP 
.RE
.PP

.SS "void* MCM_listenerThread (void * args)"

.PP
Thread for listening to messages coming from the general multicast group\&. This thread waits for new messages to be received\&. Then puts the valid messages into the parser's inbox\&. 
.PP
\fBParameters:\fP
.RS 4
\fIargs\fP Receives a the socket and the address of the group via structure\&. 
.RE
.PP

.SS "void* MCM_senderThread (void * args)"

.PP
Thread for sending the messages to the station multicast group\&. Waits for messages in the outbox of the station group ands sends those messages\&. 
.SS "void MCM_shutdownMcastServer ()"

.PP
Close the sockets and stop all threads of multicast comunication\&. Gracefully shutdowns and then closes all the involved sockets\&. Then, stops the listener and sender thread\&. 
.SH "Variable Documentation"
.PP 
.SS "\fBMCM_serverStats\fP mcmServerStats"

.PP
Variable to store all the multicast server info\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for Skynet - Emergency station from the source code\&.
