.TH "MCM_serverStats" 3 "Thu Jan 21 2016" "Version 0.1" "Emergency station" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MCM_serverStats \- Structure to store all the information abount the multicast communications server\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <structures\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBstate\fP"
.br
.RI "\fIState of the multicast communications server\&. \fP"
.ti -1c
.RI "int \fBgeneralSocket\fP"
.br
.RI "\fISocket of the general multicast group\&. \fP"
.ti -1c
.RI "int \fBstationSocket\fP"
.br
.RI "\fISocket of the station multicast group\&. \fP"
.ti -1c
.RI "struct ip_mreq \fBgeneralMreq\fP"
.br
.RI "\fIStructure containing the general group information\&. \fP"
.ti -1c
.RI "struct ip_mreq \fBstationMreq\fP"
.br
.RI "\fIStructure containing the station group information\&. \fP"
.ti -1c
.RI "struct in_addr \fBgeneralGroup\fP"
.br
.RI "\fIAddress of the general group\&. \fP"
.ti -1c
.RI "struct in_addr \fBstationGroup\fP"
.br
.RI "\fIAddress of the station group\&. \fP"
.ti -1c
.RI "\fBPMSGBUFF\fP \fBgeneralInbox\fP"
.br
.RI "\fIInbox for the messages coming from the general group\&. \fP"
.ti -1c
.RI "\fBPMSGBUFF\fP \fBstationOutbox\fP"
.br
.RI "\fIOutbox for the messages to be sent to the station group\&. \fP"
.ti -1c
.RI "pthread_t \fBlistenThread\fP"
.br
.RI "\fIThreat to listen to the messages from the general group\&. \fP"
.ti -1c
.RI "pthread_t \fBsendThread\fP"
.br
.RI "\fIThread to send the messages to the station group\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Structure to store all the information abount the multicast communications server\&. 
.SH "Field Documentation"
.PP 
.SS "struct in_addr generalGroup"

.PP
Address of the general group\&. 
.SS "\fBPMSGBUFF\fP generalInbox"

.PP
Inbox for the messages coming from the general group\&. 
.SS "struct ip_mreq generalMreq"

.PP
Structure containing the general group information\&. 
.SS "int generalSocket"

.PP
Socket of the general multicast group\&. 
.SS "pthread_t listenThread"

.PP
Threat to listen to the messages from the general group\&. 
.SS "pthread_t sendThread"

.PP
Thread to send the messages to the station group\&. 
.SS "int state"

.PP
State of the multicast communications server\&. 0 - Stop, 1 - Active\&. 
.SS "struct in_addr stationGroup"

.PP
Address of the station group\&. 
.SS "struct ip_mreq stationMreq"

.PP
Structure containing the station group information\&. 
.SS "\fBPMSGBUFF\fP stationOutbox"

.PP
Outbox for the messages to be sent to the station group\&. 
.SS "int stationSocket"

.PP
Socket of the station multicast group\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Emergency station from the source code\&.
