.TH "MESSAGE" 3 "Mon Jan 25 2016" "Version 0.1" "Skynet - Emergency station" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MESSAGE \- Structure where the messages are stored\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <structures\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBsource\fP"
.br
.RI "\fISource of the message\&. \fP"
.ti -1c
.RI "in_addr_t \fBsrcAddress\fP"
.br
.RI "\fISource address of the message\&. \fP"
.ti -1c
.RI "int \fBclientSocket\fP"
.br
.RI "\fISocket where the message come from\&. \fP"
.ti -1c
.RI "pthread_t \fBhandlingThread\fP"
.br
.RI "\fIThread that has handled the incoming message\&. \fP"
.ti -1c
.RI "int \fBisFirstMsg\fP"
.br
.RI "\fITells if this is the first received message from a vehicle\&. \fP"
.ti -1c
.RI "int \fBmsgSize\fP"
.br
.RI "\fISize of the message\&. \fP"
.ti -1c
.RI "char * \fBfullMsg\fP"
.br
.RI "\fIFull message with all the fields on it\&. \fP"
.ti -1c
.RI "char * \fBid\fP"
.br
.RI "\fIID field of the message\&. \fP"
.ti -1c
.RI "char * \fBdataType\fP"
.br
.RI "\fIType field of the message\&. \fP"
.ti -1c
.RI "char * \fBdata\fP"
.br
.RI "\fIData field of the message\&. \fP"
.ti -1c
.RI "char * \fBmsgCounter\fP"
.br
.RI "\fICounter field of the message\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Structure where the messages are stored\&. 
.SH "Field Documentation"
.PP 
.SS "int clientSocket"

.PP
Socket where the message come from\&. 
.SS "char* data"

.PP
Data field of the message\&. 
.SS "char* dataType"

.PP
Type field of the message\&. 
.SS "char* fullMsg"

.PP
Full message with all the fields on it\&. 
.SS "pthread_t handlingThread"

.PP
Thread that has handled the incoming message\&. 
.SS "char* id"

.PP
ID field of the message\&. 
.SS "int isFirstMsg"

.PP
Tells if this is the first received message from a vehicle\&. 
.SS "char* msgCounter"

.PP
Counter field of the message\&. (Unused) 
.SS "int msgSize"

.PP
Size of the message\&. 
.SS "int source"

.PP
Source of the message\&. 0 - Sever, 1 - Vehicle\&. 
.SS "in_addr_t srcAddress"

.PP
Source address of the message\&. (Unused) 

.SH "Author"
.PP 
Generated automatically by Doxygen for Skynet - Emergency station from the source code\&.
