.TH "rasPi-EmergencyStation/msgBuffers.c" 3 "Mon Jan 25 2016" "Version 0.1" "Skynet - Emergency station" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rasPi-EmergencyStation/msgBuffers.c \- File containing the definitions of all functions related to the message mailboxes\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'msgBuffers\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBPMSGBUFF\fP \fBMB_initBuffer\fP (int maxVals)"
.br
.RI "\fICreate a new buffer or mailbox and initialize it for n values\&. \fP"
.ti -1c
.RI "void \fBMB_putMessage\fP (\fBPMSGBUFF\fP buffer, \fBPMESSAGE\fP msg)"
.br
.RI "\fIPut a message into the buffer\&. \fP"
.ti -1c
.RI "\fBPMESSAGE\fP \fBMB_getMessage\fP (\fBPMSGBUFF\fP buffer)"
.br
.RI "\fIGet a message from the buffer\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
File containing the definitions of all functions related to the message mailboxes\&. 


.SH "Function Documentation"
.PP 
.SS "\fBPMESSAGE\fP MB_getMessage (\fBPMSGBUFF\fP buffer)"

.PP
Get a message from the buffer\&. This function will get a message from the selected buffer and return it's pointer\&. If the buffer is empty, it will wait for a value to be available\&. 
.PP
\fBParameters:\fP
.RS 4
\fIbuffer\fP The buffer to get the message\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
The pointer to the adquired message\&. 
.RE
.PP

.SS "\fBPMSGBUFF\fP MB_initBuffer (int maxVals)"

.PP
Create a new buffer or mailbox and initialize it for n values\&. This function creates a new buffer by allocating all the memory, mutexes and values needed and returns the pointer to the newly created buffer\&. 
.PP
\fBParameters:\fP
.RS 4
\fImaxVals\fP The maximum number of values\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
The pointer to the new buffer structure\&. 
.RE
.PP

.SS "void MB_putMessage (\fBPMSGBUFF\fP buffer, \fBPMESSAGE\fP msg)"

.PP
Put a message into the buffer\&. This function puts a message passed by parameter into the chosen buffer\&. If the buffer is full it will wait until there's space on it\&. 
.PP
\fBParameters:\fP
.RS 4
\fIbuffer\fP The buffer to put the message into\&. 
.br
\fImsg\fP The message to put in the buffer\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Skynet - Emergency station from the source code\&.
