.TH "MSGBUFF" 3 "Fri Jan 22 2016" "Version 0.1" "Skynet - Emergency station" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MSGBUFF \- Message mailbox/buffer main structure\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <structures\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "pthread_mutex_t \fBmtx\fP"
.br
.RI "\fIMutex used for single thread access to the mailbox\&. \fP"
.ti -1c
.RI "pthread_cond_t \fBempty\fP"
.br
.RI "\fIEmpty condition\&. \fP"
.ti -1c
.RI "pthread_cond_t \fBfull\fP"
.br
.RI "\fIFull condition\&. \fP"
.ti -1c
.RI "int \fBcant\fP"
.br
.RI "\fIQuantity of elements in the mailbox\&. \fP"
.ti -1c
.RI "int \fBmaxVals\fP"
.br
.RI "\fIMaximum values that can be stored in the mailbox\&. \fP"
.ti -1c
.RI "\fBPMSGQUEUE\fP \fBhead\fP"
.br
.RI "\fIHead node of the mailbox\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Message mailbox/buffer main structure\&. 
.SH "Field Documentation"
.PP 
.SS "int cant"

.PP
Quantity of elements in the mailbox\&. 
.SS "pthread_cond_t empty"

.PP
Empty condition\&. 
.SS "pthread_cond_t full"

.PP
Full condition\&. 
.SS "\fBPMSGQUEUE\fP head"

.PP
Head node of the mailbox\&. 
.SS "int maxVals"

.PP
Maximum values that can be stored in the mailbox\&. 
.SS "pthread_mutex_t mtx"

.PP
Mutex used for single thread access to the mailbox\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Skynet - Emergency station from the source code\&.
