.TH "structures.h" 3 "Fri Jan 22 2016" "Version 0.1" "Skynet - Emergency station" \" -*- nroff -*-
.ad l
.nh
.SH NAME
structures.h \- File containing all the structure definitions used in the other modules\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <pthread\&.h>\fP
.br
\fC#include <netinet/in\&.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBMP_RECEIVERSTR\fP"
.br
.RI "\fIStructure used in the message receiver function to store it's state\&. \fP"
.ti -1c
.RI "struct \fBMESSAGE\fP"
.br
.RI "\fIStructure where the messages are stored\&. \fP"
.ti -1c
.RI "struct \fBMSGQUEUE\fP"
.br
.RI "\fINode element structure of the message mailbox/buffer\&. \fP"
.ti -1c
.RI "struct \fBMSGBUFF\fP"
.br
.RI "\fIMessage mailbox/buffer main structure\&. \fP"
.ti -1c
.RI "struct \fBSA_VEHICLE_DATA\fP"
.br
.RI "\fIStructure to store the vehicles connected to the station\&. \fP"
.ti -1c
.RI "struct \fBSA_VEHICLE_ELEM\fP"
.br
.RI "\fINode element structure of the vehicle list\&. \fP"
.ti -1c
.RI "struct \fBSA_VEHICLE_QUEUE\fP"
.br
.RI "\fIStructure of the queue to store all the vehicles\&. \fP"
.ti -1c
.RI "struct \fBSSC_STAT\fP"
.br
.RI "\fIStructure to store all the parameters used by the connection to the server\&. \fP"
.ti -1c
.RI "struct \fBVSC_STAT\fP"
.br
.RI "\fIStructure to store the parameters of the vehicle communication server\&. \fP"
.ti -1c
.RI "struct \fBMCM_threadStruct\fP"
.br
.RI "\fIStructure to pass to the multicast communication threads\&. \fP"
.ti -1c
.RI "struct \fBMCM_serverStats\fP"
.br
.RI "\fIStructure to store all the information abount the multicast communications server\&. \fP"
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBMP_RECEIVERSTR\fP \fBMP_RECEIVERSTR\fP"
.br
.RI "\fIStructure used in the message receiver function to store it's state\&. \fP"
.ti -1c
.RI "typedef struct \fBMP_RECEIVERSTR\fP * \fBMP_PRECEIVERSTR\fP"
.br
.ti -1c
.RI "typedef struct \fBMESSAGE\fP \fBMESSAGE\fP"
.br
.RI "\fIStructure where the messages are stored\&. \fP"
.ti -1c
.RI "typedef struct \fBMESSAGE\fP * \fBPMESSAGE\fP"
.br
.ti -1c
.RI "typedef struct \fBMSGQUEUE\fP \fBMSGQUEUE\fP"
.br
.RI "\fINode element structure of the message mailbox/buffer\&. \fP"
.ti -1c
.RI "typedef struct \fBMSGQUEUE\fP * \fBPMSGQUEUE\fP"
.br
.ti -1c
.RI "typedef struct \fBMSGBUFF\fP \fBMSGBUFF\fP"
.br
.RI "\fIMessage mailbox/buffer main structure\&. \fP"
.ti -1c
.RI "typedef struct \fBMSGBUFF\fP * \fBPMSGBUFF\fP"
.br
.ti -1c
.RI "typedef struct \fBSA_VEHICLE_DATA\fP \fBSA_VEHICLE_DATA\fP"
.br
.RI "\fIStructure to store the vehicles connected to the station\&. \fP"
.ti -1c
.RI "typedef struct \fBSA_VEHICLE_DATA\fP * \fBSA_PVEHICLE_DATA\fP"
.br
.ti -1c
.RI "typedef struct \fBSA_VEHICLE_ELEM\fP \fBSA_VEHICLE_ELEM\fP"
.br
.RI "\fINode element structure of the vehicle list\&. \fP"
.ti -1c
.RI "typedef struct \fBSA_VEHICLE_ELEM\fP * \fBSA_PVEHICLE_ELEM\fP"
.br
.ti -1c
.RI "typedef struct \fBSA_VEHICLE_QUEUE\fP \fBSA_VEHICLE_LIST\fP"
.br
.RI "\fIStructure of the queue to store all the vehicles\&. \fP"
.ti -1c
.RI "typedef struct \fBSA_VEHICLE_QUEUE\fP * \fBSA_PVEHICLE_QUEUE\fP"
.br
.ti -1c
.RI "typedef struct \fBSSC_STAT\fP \fBSSC_STAT\fP"
.br
.RI "\fIStructure to store all the parameters used by the connection to the server\&. \fP"
.ti -1c
.RI "typedef struct \fBSSC_STAT\fP * \fBSSC_PSTAT\fP"
.br
.ti -1c
.RI "typedef struct \fBVSC_STAT\fP \fBVSC_STAT\fP"
.br
.RI "\fIStructure to store the parameters of the vehicle communication server\&. \fP"
.ti -1c
.RI "typedef struct \fBVSC_STAT\fP * \fBVSC_PSTAT\fP"
.br
.ti -1c
.RI "typedef struct \fBMCM_threadStruct\fP \fBMCM_threadStruct\fP"
.br
.RI "\fIStructure to pass to the multicast communication threads\&. \fP"
.ti -1c
.RI "typedef struct \fBMCM_serverStats\fP \fBMCM_serverStats\fP"
.br
.RI "\fIStructure to store all the information abount the multicast communications server\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
File containing all the structure definitions used in the other modules\&. 


.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fBMCM_serverStats\fP \fBMCM_serverStats\fP"

.PP
Structure to store all the information abount the multicast communications server\&. 
.SS "typedef struct \fBMCM_threadStruct\fP \fBMCM_threadStruct\fP"

.PP
Structure to pass to the multicast communication threads\&. 
.SS "typedef struct \fBMESSAGE\fP \fBMESSAGE\fP"

.PP
Structure where the messages are stored\&. 
.SS "typedef struct \fBMP_RECEIVERSTR\fP * \fBMP_PRECEIVERSTR\fP"

.SS "typedef struct \fBMP_RECEIVERSTR\fP \fBMP_RECEIVERSTR\fP"

.PP
Structure used in the message receiver function to store it's state\&. 
.SS "typedef struct \fBMSGBUFF\fP \fBMSGBUFF\fP"

.PP
Message mailbox/buffer main structure\&. 
.SS "typedef struct \fBMSGQUEUE\fP \fBMSGQUEUE\fP"

.PP
Node element structure of the message mailbox/buffer\&. 
.SS "typedef struct \fBMESSAGE\fP * \fBPMESSAGE\fP"

.SS "typedef struct \fBMSGBUFF\fP * \fBPMSGBUFF\fP"

.SS "typedef struct \fBMSGQUEUE\fP * \fBPMSGQUEUE\fP"

.SS "typedef struct \fBSA_VEHICLE_DATA\fP * \fBSA_PVEHICLE_DATA\fP"

.SS "typedef struct \fBSA_VEHICLE_ELEM\fP * \fBSA_PVEHICLE_ELEM\fP"

.SS "typedef struct \fBSA_VEHICLE_QUEUE\fP * \fBSA_PVEHICLE_QUEUE\fP"

.SS "typedef struct \fBSA_VEHICLE_DATA\fP \fBSA_VEHICLE_DATA\fP"

.PP
Structure to store the vehicles connected to the station\&. 
.SS "typedef struct \fBSA_VEHICLE_ELEM\fP \fBSA_VEHICLE_ELEM\fP"

.PP
Node element structure of the vehicle list\&. 
.SS "typedef struct \fBSA_VEHICLE_QUEUE\fP \fBSA_VEHICLE_LIST\fP"

.PP
Structure of the queue to store all the vehicles\&. 
.SS "typedef struct \fBSSC_STAT\fP * \fBSSC_PSTAT\fP"

.SS "typedef struct \fBSSC_STAT\fP \fBSSC_STAT\fP"

.PP
Structure to store all the parameters used by the connection to the server\&. 
.SS "typedef struct \fBVSC_STAT\fP * \fBVSC_PSTAT\fP"

.SS "typedef struct \fBVSC_STAT\fP \fBVSC_STAT\fP"

.PP
Structure to store the parameters of the vehicle communication server\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for Skynet - Emergency station from the source code\&.
